apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  template:
    metadata:
      name: db-noticias
      labels:
        app: db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          # env:
          #   - name: "MYSQL_ROOT_PASSWORD"
          #     value: "q1w2e3r4"
          #   - name: "MYSQL_DATABASE"
          #     value: "empresa"
          #   - name: "MYSQL_PASSWORD"
          #     value: "q1w2e3r4"
          # env:
          #   - name: MYSQL_ROOT_PASSWORD
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-configmap
          #         key: MYSQL_ROOT_PASSWORD
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
      app: db-noticias
